### ISSUE TITLE
Admin/SetupCompany: Search not working

### ISSUE THREAD

**Issue by nolann-dev** [lidi-team/backend#36]
return all project not by search text

**Comment by TungBeo199x** [comment]
resolved

**Comment by nolann-dev** [comment]
![image](https://user-images.githubusercontent.com/56147592/100084149-fd92a280-2e7c-11eb-9aa4-de04eab44963.png)
Searching in 4 tabs is not working.

**Comment by TungBeo199x** [comment]
Anh @vinhtt95 vào giải quyết trường hợp này hộ em phát

**Comment by vinhtt95** [comment]
Mấy cái này chỉ có crud, ko có search. Theo order của Nam

**Comment by nolann-dev** [comment]
![image](https://user-images.githubusercontent.com/56147592/100261969-18990b80-2f7e-11eb-94f0-55a4662a62cd.png)
@vinhtt95

**Comment by TungBeo199x** [comment]
reviewed
