### ISSUE TITLE
admin/project: update project wrong response

### ISSUE THREAD

**Issue by nolann-dev** [lidi-team/backend#51]
![image](https://user-images.githubusercontent.com/56147592/100550715-4b107480-32ae-11eb-8ee8-a8c49c2d4b02.png)
update success but response fail

**Comment by nolann-dev** [comment]
should: Rename parentProjectId to parentId

**Comment by nolann-dev** [comment]
bug: cannot update pmId

**Comment by TungBeo199x** [comment]
solved

**Comment by nolann-dev** [comment]
done
