### ISSUE TITLE
API cfrs/list-waiting with page = 10000, 20000 still works and if page = -1, result should be 404 error, but 406 now

### ISSUE THREAD

**Issue by hoangledinh65** [lidi-team/backend#56]

**Comment by TungBeo199x** [comment]
page = 10000, 20000 vẫn trả ra kết quả ko phải sai đâu nhé. nó trả ra kết  quả theo phân trang, đến trang 10000, 20000 ko có data, trả ra list rỗng là đúng r.
đã sửa: page <= 0. => bắn error
